# SPDX-FileCopyrightText: 2022-present Intel Corporation
# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Disable 4G Control Plane
omec-control-plane:
  enable4G: false

# Disable 5G RAN Simulator
5g-ran-sim:
  enable: false
  
# Override values for 5g-control-plane Helm Chart
# https://gerrit.opencord.org/sdcore-helm-charts/5g-control-plane/values.yaml
5g-control-plane:
  enable5G: true
  images:
    repository: "registry.opennetworking.org/docker.io/"
    #tags:
    #  amf: <amf image tag>
    # refer to above Helm Chart to add other NF images

  kafka:
    deploy: true

  mongodb:
    usePassword: false
    persistence:
      enabled: false
    architecture: replicaset
    replicaCount: 2
  resources:
    enabled: false

  config:
    mongodb:
      name: free5gc
      url: mongodb://mongodb-arbiter-headless #enable if cluster deployment required

    managedByConfigPod:
      enabled: true
      syncUrl: http://sdcore-adapter-v2-1.aether-roc.svc:8080/synchronize

    sctplb:
      deploy: false # if enabled then deploy sctp pod. 
                    # Once backend is stable, this option will be enabled by default

    upfadapter:
      deploy: false # If enabled then deploy upf adapter pod. 
                    # Once backend is stable, this option will be enabled by default

    metricfunc:
      deploy: true
      cfgFiles:
        metricscfg.conf:
          configuration:
            nfStreams:
              - topic:
                  topicGroup: analytics
                  topicName: sdcore-data-source-amf
                urls:
                  - uri: kafka-headless.omec.svc
                    port: 9092
              - topic:
                  topicGroup: analytics
                  topicName: sdcore-data-source-smf
                urls:
                  - uri: kafka-headless.omec.svc
                    port: 9092

    # AMF config override.
    amf:
      # Use externalIP if you need to access AMF from remote setup 
      # and you don't want setup NodePort Service Type
      ngapp:
        externalIp: {{ ansible_default_ipv4.address }}
        port: 38412
      cfgFiles:
        amfcfg.conf:
          configuration:
            # storing AMF subscribers in the datastore is disabled by default. 
            # Once internal testing is complete we will enable DBStore by default.
            enableDBStore: false
            kafkaInfo:
              brokerUri: kafka-headless.omec.svc
              brokerPort: 9092

    # SMF config override.
    smf:
      cfgFiles:
        smfcfg.conf:
          configuration:
            # Storing AMF subscribers in the datastore is disabled by default. 
            # Once internal testing is complete we will enable DBStore by default.
            enableDBStore: false
            kafkaInfo:
              enableKafka: true
              brokerUri: kafka-headless.omec.svc
              brokerPort: 9092

    #pcf:
    #  cfgFiles:
    #    pcfcfg.conf:
    #      configuration:

    nrf:
      cfgFiles:
        nrfcfg.conf:
          configuration:
            mongoDBStreamEnable: false    # enable/disable MongoDB stream in NRF.
            nfProfileExpiryEnable: false  # if enabled, remove NF profile if no keepalive received
            nfKeepAliveTime: 60           # default timeout for NF profiles


# Override values for omec-sub-provision (subscriber) Helm Chart
# https://gerrit.opencord.org/sdcore-helm-charts/omec-sub-provision/values.yaml
# ***Note: Most of these values can (and should) be set via ROC API***
omec-sub-provision:
  enable: true
  images:
    repository: "registry.opennetworking.org/docker.io/"
    #tags:
    #  simapp: #add simapp override image

  config:
    simapp:
      cfgFiles:
        simapp.yaml:
          configuration:
            provision-network-slice: {{ core.standalone }} # if enabled, Device Groups & Slices configure by simapp
            sub-provision-endpt:
              addr: webui.omec.svc.cluster.local  # subscriber configuation endpoint.
            # sub-proxy-endpt:  # used if subscriber proxy is enabled in the ROC.
            #   addr: subscriber-proxy.aether-roc.svc.cluster.local
            #   port: 5000

            # Configure Subscriber IMSIs and their security details.
            # You can have any number of subscriber ranges
            # This block is always necessary to establish range(s) of valid IMSIs
            subscribers:
            - ueId-start: "001010123456864"
              ueId-end: "001010123456868"
              plmnId: "00101"
              opc: "00000000000000000000000000000000"
              op: ""
              key: "ffffffffffffffffffffffffffffffff"
              sequenceNumber: "16f3b3f70fc2"

            # Configure Device Groups (ignored if provision-network-slice is disabled)
            device-groups:
            - name:  "5g-user-group1"
              imsis:
                - "001010123456864"
                - "001010123456865"
              ip-domain-name: "pool1"
              ip-domain-expanded:
                dnn: internet
                dns-primary: "8.8.8.8"        # Value is sent to UE
                mtu: 1460                     # Value is sent to UE when PDU Session Established
                ue-ip-pool: "172.250.1.0/16"  # IP address pool for subscribers
                ue-dnn-qos:
                  dnn-mbr-downlink: 200000000 # UE level downlink QoS
                  dnn-mbr-uplink:    20000000 # UE level uplink QoS
                  bitrate-unit: bps           # Unit for above QoS rates
                  traffic-class:              # Default bearer QCI/ARP (not used in 5G)
                    name: "platinum"
                    qci: 9
                    arp: 6
                    pdb: 300
                    pelr: 6
              site-info: "enterprise"
            # UPF allocates IP address if there is only 1 device-group
            # SMF allocates IP address if there is >1 device-group

            # Configure Network Slices (ignored if provision-network-slice is disabled)
            network-slices:
            - name: "default"      # can be any unique slice name
              slice-id:            # must match with slice configured in gNB, UE
                sd: "010203"
                sst: 1
              site-device-group:
              - "5g-user-group1"   # All UEs in this device-group are assigned to this slice
              # Applicaiton filters control what each user can access.
              # Default, allow access to all applications
              application-filtering-rules:
              - rule-name: "ALLOW-ALL"
                priority: 250
                action: "permit"
                endpoint: "0.0.0.0/0"
              site-info:
                # Provide gNBs and UPF details and also PLMN for the site
                gNodeBs:
                - name: "gnb1"
                  tac: 1
                - name: "gnb2"
                  tac: 2
                plmn:
                  mcc: "001"
                  mnc: "01"
                site-name: "enterprise"
                upf:
                  upf-name: "upf"  # associated UPF for this slice. One UPF per Slice.
                  upf-port: 8805

# Override values for omec-user-plane Helm Chart
# https://gerrit.opencord.org/sdfabric-helm-charts/bess-upf/values.yaml
omec-user-plane:
  enable: true
  nodeSelectors:
    enabled: true
  resources:
    enabled: false
  images:
    repository: "registry.opennetworking.org/docker.io/"
    # following two lines pull busybox from Docker Hub instead of Aether Registry
    tags:
      tools: busybox:stable
    # uncomment following section to add update bess image tag
    #tags:
    #  bess: <bess image tag>
    #  pfcpiface: <pfcp image tag>
  config:
    upf:
      name: "oaisim"
      sriov:
        enabled: false    # SRIOV is disabled by default
      hugepage:
        enabled: false    # Should be enabled if DPDK is enabled
      cniPlugin: macvlan  # Can be any other plugin. Dictates how IP address are assigned
      ipam: static
      routes:
        - to: {{ ansible_default_ipv4.address }}
          via: 169.254.1.1
      enb:
        subnet: {{ ran_subnet }} # Subnet for the gNB network
      access:
        iface: {{ core.data_iface }}
      core:
        iface: {{ core.data_iface }}
      cfgFiles:
        upf.json:
          mode: af_packet     # This mode implies no DPDK
          hwcksum: true
          log_level: "trace"
          measure_upf: true
          measure_flow: true
          gtppsc: true        # Extension header enabled in 5G.
          cpiface:
            dnn: "internet"              # Must match Slice dnn
            hostname: "upf"
            #http_port: "8080"
            enable_ue_ip_alloc: false    # If true, UPF allocates address from following pool
            ue_ip_pool: "172.250.0.0/16" # IP pool used UEs if enable_ue_ip_alloc=true
